modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
[[mods]]
modId="jarjarbinks"
version="${file.jarVersion}" #
displayName="Jar Jar Binks Mod"
logoFile="icon.png"
authors="AzureDoom"
description='''
A revival of my old Jar Jar Binks mod.
'''
[[dependencies.jarjarbinks]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jarjarbinks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jarjarbinks]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.4,)"
    ordering="NONE"
    side="BOTH"
