modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
[[mods]]
modId="jarjarbinks"
version="${file.jarVersion}" #
displayName="Jar Jar Binks Mod"
logoFile="icon.png"
authors="AzureDoom"
description='''
A revival of my old Jar Jar Binks mod.
'''
[[dependencies.jarjarbinks]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jarjarbinks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jarjarbinks]]
    modId="azurelib"
    mandatory=true
    versionRange="[1.0.11,)"
    ordering="NONE"
    side="BOTH"
